### ISSUE TITLE
Decoder decodes custom types with no fields as foreign types on the Erlang target

### ISSUE THREAD

**Issue by MystPi** [MystPi/pprint#2]
Basically, instead of a custom type with no fields such as `Foo` being decoded as `TCustom("Foo", [])` on the erl target, it is decoded as `TForeign("Foo")`. This must be due to the way custom types are represented in Gleam under the hood. Don't know much about this, so calling in the erl master @giacomocavalieri.

**Comment by MystPi** [comment]
@giacomocavalieri not sure if you've seen this.

**Comment by giacomocavalieri** [comment]
Oops sorry I totally forgot to look into it! I'll have a look now 😁

**Comment by giacomocavalieri** [comment]
So I tried writing a test to reproduce this failing case but couldn't get it to produce a wrong result:
```gleam
// this passes
pub fn custom_type_decoding_test() {
  Foo(1, "a", "a")
  |> dynamic.from
  |> decoder.classify
  |> should.equal(
    TCustom("Foo", [
      Positional(value: dynamic.from(1)),
      Labelled(label: "bar", value: dynamic.from("a")),
      Labelled(label: "baz", value: dynamic.from("a")),
    ]),
  )
}
```
Is the type that gets decoded as a `TForeign` actually named `Foo` or something else?

**Comment by MystPi** [comment]
The type must have no fields to be decoded as a `TForeign`. The type you are trying has three fields.

I should've been more clear in the description, sorry!

**Comment by giacomocavalieri** [comment]
Even with no fields I still get the test working:
```gleam
// This passes
pub fn custom_type_decoding_test() {
  Wibble
  |> dynamic.from
  |> decoder.classify
  |> should.equal(decoder.TCustom("Wibble", []))
}
```
What's the type you encountered this behaviour with?

**Comment by MystPi** [comment]
Oh the gleam.toml has target=javascript in it. You'll have to run with target=erlang

**Comment by giacomocavalieri** [comment]
Ooh that explains why I couldn't get it to fail 🤦🏻 Sorry for that! Now the test is failing, thanks for your patience 💕

**Comment by MystPi** [comment]
No worries! It's probably my fault in the first place. Don't know why the config is set to JavaScript.
