### ISSUE TITLE
Invalid syntax: empty list breaks into new line with comma in edge case

### ISSUE THREAD

**Issue by JonasGruenwald** [MystPi/pprint#5]
Hello! thank you for your work on this package 🌟  

I found a case in which pprint breaks an empty list into a new line and adds a comma inside it, which is invalid Gleam syntax.

As far as I can tell this only happens in an Erlang map, in which the empty list is the value, which is how the gleam/set module is implemented.

Reproduction:
```gleam
import gleam/io
import gleam/set
import pprint

pub fn main() {
  set.new()
  |> set.insert(
    "Some item with a lot of text in this set so that a new line is forced",
  )
  |> pprint.format
  |> io.println
}
```

Output:
```gleam
Set(dict.from_list([
  #("Some item with a lot of text in this set so that a new line is forced", [
    ,  // <--- this comma is not valid gleam
  ]),
]))
```

Expected output:
```gleam
Set(dict.from_list([
  #("Some item with a lot of text in this set so that a new line is forced", [
  ]),
]))
```
(or something like that, without the `,`)

**Comment by MystPi** [comment]
Thanks for the report! The bug is fixed in the latest 1.0.4 release.
